### ISSUE TITLE
Only the first 100 repositories are backed up

### ISSUE THREAD

**Issue by shlomif** [stevieb9/github-backup#3]
Hi!

My @shlomif account has 572 repositories and only the first 100 (up to the Cs) are getting backed up by this script:

```
#!/bin/bash
export GITHUB_TOKEN='elided'
github_backup \
    -u shlomif \
    -d Backup/github_backup \
    -r \
    -i
```

I still get an issues sub-dir. Please look into fixing it.

**Comment by stevieb9** [comment]
Thank you for the report. I'll look into whether this is a restriction of
the API or otherwise.

**Comment by shlomif** [comment]
Thanks!

**Comment by shlomif** [comment]
I should note that it appears that https://github.com/ddollar/github-backup does not appear to exhibit the same problem:

```
shlomif@telaviv1:~/Backup/github_backup-rb$ ls -l shlomif/ | wc -l
576

```

perhaps take a look there.

**Comment by shlomif** [comment]
Thanks, @stevieb9 !
